# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c923e6b764457ff5dd7bc9f0569a879fa20a32e1c72cdd315595bc938831472c9bc58d30479034acf156ef817e5a4907bd8580c825e22ccb23a123c2aebcc99b

test:
  secret_key_base: c76767f296ee2e708902e9e5386cb53a997aeb7ba01074a2f5d112e05bfc1110819502ef2248c84aa3feaf9d4a4ea3f241053c20d3cf8b245f5a1eb11b1e0fd2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
